set nocompatible " Tells Vim NOT to act like Vi

syntax enable " (co-operative)
" syntax on (aggressive)

filetype plugin on " configures Vim options according to filetype
filetype indent on " configures idententation according to filetype

let mapleader = " "

set tabstop=4
set shiftwidth=4
set expandtab

" Enables incremental and highlight search
set incsearch
set hlsearch

" Useful cmds that give info on what im doing in vim
set showmode
set showcmd
set ruler
set number

" Provides a horizontal nav bar for cmd auto-completion
set wildmenu

silent! nohlsearch " Clears highlights after sourcing vimrc

nnoremap ; <S-:>| " Remaps ';' to 'SHIFT + :' when in NORMAL mode
inoremap jk <Esc>| " Remaps 'j, k' to 'ESCAPE' when in INSERT mode
